import { Patient } from '@/types';

/** Pacientes simulados para demostracion cuando Firestore esta vacio. */
export const MOCK_PATIENTS: Patient[] = [
  {
    _id: 'mock-1',
    name: 'Carlos Rivera Mendoza',
    age: 67,
    gender: 'M',
    bed: 'UCI-04',
    status: 'critical',
    triageLevel: 1,
    medicalHistory: 'Hipertension arterial, Diabetes Mellitus tipo 2',
    currentMedications: ['Metformina 850mg', 'Losartan 50mg', 'Insulina Glargina'],
    allergies: ['Penicilina'],
    insuranceProvider: 'IMSS',
    insurancePolicyNumber: 'IMSS-2847591',
    admissionDate: new Date().toISOString(),
    admissionReason: 'Infarto agudo al miocardio con elevacion del segmento ST',
    attendingDoctor: 'Dr. Martinez',
    previousNotes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'mock-2',
    name: 'Maria Elena Torres',
    age: 45,
    gender: 'F',
    bed: 'MED-12',
    status: 'warning',
    triageLevel: 2,
    medicalHistory: 'Asma bronquial cronico',
    currentMedications: ['Salbutamol inhalado', 'Fluticasona'],
    allergies: ['Sulfonamidas'],
    insuranceProvider: 'GNP',
    insurancePolicyNumber: 'GNP-38291',
    admissionDate: new Date().toISOString(),
    admissionReason: 'Crisis asmatica severa con desaturacion',
    attendingDoctor: 'Dr. Martinez',
    previousNotes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'mock-3',
    name: 'Jose Luis Hernandez',
    age: 52,
    gender: 'M',
    bed: 'CIR-07',
    status: 'stable',
    triageLevel: 3,
    medicalHistory: 'Colecistitis cronica litiasica',
    currentMedications: ['Ketorolaco 30mg', 'Omeprazol 40mg'],
    allergies: [],
    insuranceProvider: 'MetLife',
    insurancePolicyNumber: 'ML-49281',
    admissionDate: new Date().toISOString(),
    admissionReason: 'Postoperatorio de colecistectomia laparoscopica',
    attendingDoctor: 'Dr. Martinez',
    previousNotes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'mock-4',
    name: 'Ana Patricia Gomez',
    age: 34,
    gender: 'F',
    bed: 'GIN-02',
    status: 'stable',
    triageLevel: 3,
    medicalHistory: 'Sin antecedentes patologicos relevantes',
    currentMedications: ['Acido folico', 'Sulfato ferroso'],
    allergies: ['Ibuprofeno'],
    insuranceProvider: 'AXA',
    insurancePolicyNumber: 'AXA-58201',
    admissionDate: new Date().toISOString(),
    admissionReason: 'Amenaza de parto pretermino - 34 SDG',
    attendingDoctor: 'Dr. Martinez',
    previousNotes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'mock-5',
    name: 'Roberto Sanchez Diaz',
    age: 71,
    gender: 'M',
    bed: 'UCI-08',
    status: 'critical',
    triageLevel: 1,
    medicalHistory: 'EPOC, Insuficiencia cardiaca congestiva NYHA III',
    currentMedications: ['Furosemida 40mg', 'Digoxina 0.25mg', 'Enoxaparina'],
    allergies: ['Aspirina'],
    insuranceProvider: 'ISSSTE',
    insurancePolicyNumber: 'ISSSTE-72910',
    admissionDate: new Date().toISOString(),
    admissionReason: 'Edema agudo de pulmon, insuficiencia respiratoria',
    attendingDoctor: 'Dr. Martinez',
    previousNotes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'mock-6',
    name: 'Laura Cristina Perez',
    age: 28,
    gender: 'F',
    bed: 'MED-03',
    status: 'warning',
    triageLevel: 2,
    medicalHistory: 'Lupus eritematoso sistemico',
    currentMedications: ['Prednisona 10mg', 'Hidroxicloroquina 200mg'],
    allergies: [],
    insuranceProvider: 'GNP',
    insurancePolicyNumber: 'GNP-61829',
    admissionDate: new Date().toISOString(),
    admissionReason: 'Brote lupico con nefritis grado III',
    attendingDoctor: 'Dr. Martinez',
    previousNotes: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
